<?php
/**
 * @author     Sashas IT Support <support@sashas.org>
 * @copyright  2020  Sashas IT Support Inc. (http://www.extensions.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magetarian\CustomerTwoFactorAuth\ViewModel\Duo\Authentication $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="field twofactorauth-duo duo-auth">
    <iframe id="duo_iframe"></iframe>
    <input name="provider_code" value="<?=$viewModel->getProviderCode();?>" id="provider_code" type="hidden" />
    <button type="submit" name="twofactorauth-login" id="twofactorauth-duo" />
    <script type="text/x-magento-init">
    {
        "#duo_iframe": {
            "twoFactorAuthProviderDuo": {
                "host": "<?=$viewModel->getApiHost()?>",
                "sigRequest": "<?=$viewModel->getSignature()?>"
            }
        }
    }
</script>
</div>

