<?php
/**
 * @author     Sashas IT Support <support@sashas.org>
 * @copyright  2020  Sashas IT Support Inc. (http://www.extensions.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magetarian\CustomerTwoFactorAuth\ViewModel\Customer\LoginProviders $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="field password required">
    <div class="primary"><button type="submit" class="action login primary" name="send" id="send-google"><span><?= $block->escapeHtml(__('Sign In using Google')) ?></span></button></div>
</div>
