<?php
/**
 * @author     Sashas IT Support <support@sashas.org>
 * @copyright  2020  Sashas IT Support Inc. (http://www.extensions.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magetarian\CustomerTwoFactorAuth\ViewModel\Google\Authentication $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isActive()):?>
    auth
<?php else: ?>
    <div class="field twofactorauth-google google-configure google-qr">
        <img class="msp-tfa-google-qr" src="<?= $block->escapeHtmlAttr($block->getUrl('twofactorauth/google/qr',['_query' => ['customerId'=>$viewModel->getCustomerId()]])) ?>"/>
        <p class="msp-tfa-google-secure-code"><?= $block->escapeHtml($viewModel->getSecretCode()) ?></p>
        <p><?= $block->escapeHtml(__('Scan or copy&amp;paste this code with your authenticator app and insert your code to confirm.')) ?></p>
    </div>
    <div class="field twofactorauth-google google-configure google-secure-code">
        <label for="tfa_code" class="admin__field-label">
            <span data-bind='i18n: "Authenticator code"'></span>
        </label>
        <label class="label" for="tfa_code"><span><?= $block->escapeHtml(__('Authenticator code')) ?></span></label>
        <div class="control">
            <input name="tfa_code" value="" autocomplete="off" id="tfa_code" type="password" class="input-text" placeholder="Your code" title="<?= $block->escapeHtmlAttr(__('Your code')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true}">
        </div>
    </div>
    <div class="primary">
        <button type="button" class="action login primary"  name="twofactorauth-login" id="twofactorauth-google">
            <span><?= $block->escapeHtmlAttr(__('Confirm')) ?></span>
        </button>
    </div>
<?php endif; ?>
