<?php
/**
 * @author     The S Group <support@sashas.org>
 * @copyright  2020  Sashas IT Support Inc. (https://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php
// phpcs:ignoreFile
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magetarian\CustomerTwoFactorAuth\ViewModel\Customer\Information $viewModel */
$viewModel = $block->getViewModel();
$providerCode = $block->getProviderCode();
?>
<?php if ($viewModel->isEnabled($providerCode)):?>
    <?php $additionalConfig = $viewModel->getAdditionalConfig($providerCode);?>
    <div class="block block-google">
        <div class="block-title">
            <strong><?= $block->escapeHtml($viewModel->getProviderName($providerCode)) ?></strong>
        </div>
        <div class="block-content">
            <div class="box box-settings">
                <div class="box-content">
                    <img class="msp-tfa-google-qr" src="<?=$block->escapeHtmlAttr($block->getUrl('tfa/google/qr')) ?>"/>
                    <p>

                        <textarea readonly="true" class="msp-tfa-google-secure-code"><?= $block->escapeHtml($additionalConfig['secretCode']) ?></textarea>
                    </p>
                    <p><?= $block->escapeHtml(__('Scan or copy&amp;paste this code with your authenticator app and insert your code to confirm when you login.')) ?></p>
                </div>
                <form
                    class="form"
                    action="<?= $block->escapeUrl($block->getUrl('tfa/customer/resetPost')) ?>"
                    method="post">
                    <?= $block->getBlockHtml('formkey') ?>
                    <input type="hidden" name="provider" value="<?= $block->escapeHtmlAttr($providerCode) ?>" />
                    <div class="box-actions">
                        <div class="primary">
                            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Reset')) ?>"
                                    class="action primary">
                                <span><?= $block->escapeHtml(__('Reset')) ?></span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<?php endif; ?>
